# Generated by Django 3.1 on 2021-10-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210914_1755'),
        ('store', '0003_variation_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product_category',
        ),
        migrations.AddField(
            model_name='variation',
            name='product_category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
    ]
