# Generated by Django 3.1 on 2021-11-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211012_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product_category',
        ),
    ]
